spring.application.name=Istudy

spring.datasource.url=jdbc:postgresql://localhost:5432/istudy
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate

jwt.secret=troque-esta-chave-por-uma-string-bem-longa-e-aleatoria-de-producao
jwt.expiration=86400000

logging.level.org.springframework.security=DEBUG
